routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $auth=0;
    $data = Auth::user();
    if($data!=null)
    {
        $auth=1;
    }
    return view('welcome',['auth'=>$auth]);
});

Auth::routes();


Route::post('/login_user', [LoginController::class, 'login_user'])->name('login_user');

Route::get('/login', function () {
    return view('auth.login');
})->name('login');
Route::post('register', [App\Http\Controllers\Auth\RegisterController::class, 'register'])->name('register');

Route::group(['middleware'=>'auth'],function(){

    Route::get('view/profile', [App\Http\Controllers\Controller::class, 'profile_form'])->name('profile');
    Route::post('insert/profile', [App\Http\Controllers\Controller::class, 'profile_register'])->name('register_pofile');
    Route::get('update/profile/{id}', [App\Http\Controllers\Controller::class, 'profile_Update']);
    Route::get('post', [App\Http\Controllers\Post::class, 'post_form'])->name('post');

    Route::post('post', [App\Http\Controllers\Post::class, 'insert_post'])->name('insert_post');
    Route::get('view_all/post', [App\Http\Controllers\Post::class, 'view_post'])->name('view_post');

    Route::get('view/post', [App\Http\Controllers\Post::class, 'view_all_post'])->name('view_my_post');

});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::post('/reset_mail', [App\Http\Controllers\Controller::class, 'Reset_mail'])->name('password.email');
Route::get('/confirm/{id}', [App\Http\Controllers\Controller::class, 'update_password']);

Route::post('/change', [App\Http\Controllers\Controller::class, 'change_password'])->name('password.confirm');

Route::get('language/{locale}', [App\Http\Controllers\LocalizationController::class, 'index']);

app/Models/User_profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User_profile extends Model
{
    use HasFactory,SoftDeletes;
    protected $fillable=[
        'user_id',
        'gender',
        'address',
        'profile_photo',
        'birth_date'
        
    ];
    public function post()
    {
        return $this->hasOne(Post::class);
    }
    public function setAddressAttribute($value)
    {
        $this->attributes['address'] = strtoupper($value);
        //castinh
        // $this->attributes['address'] = (int)strtoupper($value);
    }
    public function getAddressAttribute($value)
    {
        return strtolower($value);
    }
    public function getFullNameAttribute()
{
    return "{$this->address} {$this->profile_photo}";
}
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
<h1 align="center">Hello {{ Auth::user()->name }} </h1>
</div>
@endsection

resources/views/profile_form.blade.php
@extends('layouts.app')

@section('content')

<div>
  @if ($message=Session::get('success'))
    {{$message}}
  @endif
</div>


 
  <form action="{{ route('register_pofile') }}" method="post" enctype="multipart/form-data">
    @csrf
    <center>
      <h1>Profile Update</h1>
      <br>
      <br>
      @foreach ($user_data as $data)
        <img src="{{ asset('storage/'.$data->profile_photo)}}" width="100" height="100">
      <table>
        <tr>
          <td>
            <input type="hidden" name="user_id" value="{{$id}}" id="user_id">
            <label>Gender</label>
          </td>
          <td> 
            Male <input type="radio" name="gender" value="male" id="gender" @if ($data->gender=="male")
              checked
            @endif>
            Female<input type="radio" name="gender" value="female" id="gender"
            @if ($data->gender=="female")
              checked
            @endif>
          </td>
        </tr>
        <tr>
          <td>
            <label>Adddress</label>
          </td>
          <td>
            <input type="text" name="address" id="address" value="{{$data->address}}">
            <!-- <input type="text" name="address" id="address" value="{{$data->full_name }}"> -->

          </td>
        </tr>
        <tr>
          <td>
            <label>Profile Photo</label>
          </td>
          <td>
            <input type="file" name="profile_photo" id="profile_photo" value="{{$data->profile_photo}}">
          </td>
        </tr>
        <tr>
          <td>
            <label>Date Of Birth</label>
          </td>
          <td>
            <input type="date" name="birth_date" id="birth_date" value="{{$data->birth_date}}">
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <input type="submit" value="Submit">
          </td>
        </tr>
      </table>
      @endforeach
    </center>

  </form>
  

  @endsection

resources/views/update_form.blade.php
@extends('layouts.app')

@section('content')

<div>
  @if ($message=Session::get('success'))
    {{$message}}
  @endif
</div>


 
  <form action="{{ route('register_pofile') }}" method="post" enctype="multipart/form-data">
    @csrf
    <center>
      <h1>Profile Add</h1>
      <br>
      <br>
 
        
      <table>
        <tr>
          <td>
            <input type="hidden" name="user_id" value="{{$id}}" id="user_id">
            <label>Gender</label>
          </td>
          <td> 
            Male <input type="radio" name="gender" value="male" id="gender" >
            Female<input type="radio" name="gender" value="female" id="gender"
          >
          </td>
        </tr>
        <tr>
          <td>
            <label>Adddress</label>
          </td>
          <td>
            <input type="text" name="address" id="address" >
          </td>
        </tr>
        <tr>
          <td>
            <label>Profile Photo</label>
          </td>
          <td>
            <input type="file" name="profile_photo" id="profile_photo" >
          </td>
        </tr>
        <tr>
          <td>
            <label>Date Of Birth</label>
          </td>
          <td>
            <input type="date" name="birth_date" id="birth_date" >
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <input type="submit" value="Submit">
          </td>
        </tr>
      </table>

    </center>

  </form>
  

  @endsection